"""order model change

Revision ID: 3a887bbf3de1
Revises: 6243e427c6a6
Create Date: 2026-01-22 23:14:15.960310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a887bbf3de1'
down_revision: Union[str, Sequence[str], None] = '6243e427c6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), server_default='employee', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
