"""pizza model changes

Revision ID: daa6923a49ad
Revises: b0034694f38c
Create Date: 2026-01-21 18:41:51.655380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa6923a49ad'
down_revision: Union[str, Sequence[str], None] = 'b0034694f38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.drop_index(op.f('ix_pizzas_id'), table_name='pizzas')
    op.drop_index(op.f('ix_pizzas_name'), table_name='pizzas')
    op.drop_table('pizzas')
    op.add_column('order_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_column('order_items', 'pizza_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('order_items', 'product_id')
    op.create_table('pizzas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pizzas_pkey'))
    )
    op.create_index(op.f('ix_pizzas_name'), 'pizzas', ['name'], unique=True)
    op.create_index(op.f('ix_pizzas_id'), 'pizzas', ['id'], unique=False)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
